# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Squashed initial migration — full final schema, no data operations.
# Generated by Django 6.0.7 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_checkout_export_to_magento_api", "0001_initial"),
        ("django_checkout_export_to_magento_api", "0002_alter_orderinmagento_checkout_order_invoiceinmagento"),
        ("django_checkout_export_to_magento_api", "0003_channel"),
        ("django_checkout_export_to_magento_api", "0004_orderinmagento_canceled"),
        ("django_checkout_export_to_magento_api", "0005_shipmentinmagento"),
        (
            "django_checkout_export_to_magento_api",
            "0006_rename_magento_store_id_channel_default_magento_store_id_and_more",
        ),
        ("django_checkout_export_to_magento_api", "0007_channel_magento_should_send_email_invoice_confirmation"),
    ]

    dependencies = [
        ("django_checkout", "0001_squashed_0083_remove_paymentintent_one_intent_per_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("label", models.CharField(default="", max_length=128, unique=True)),
                ("default_magento_store_id", models.CharField(max_length=128, unique=True)),
                ("lang_channel_to_magento_store", models.JSONField(null=True)),
                ("magento_should_send_email_invoice_confirmation", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceInMagento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("magento_url", models.CharField(max_length=255)),
                ("success", models.BooleanField(default=False)),
                ("request", models.JSONField()),
                ("response", models.JSONField(null=True)),
                ("invoice_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "checkout_payment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_in_magento",
                        to="django_checkout.paymentintent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice in Magento",
                "verbose_name_plural": "Invoices in Magento",
            },
        ),
        migrations.CreateModel(
            name="OrderInMagento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("magento_url", models.CharField(max_length=255)),
                ("success", models.BooleanField(default=False)),
                ("canceled", models.BooleanField(default=False)),
                ("request", models.JSONField()),
                ("response", models.JSONField(null=True)),
                ("entity_id", models.CharField(blank=True, max_length=100, null=True)),
                ("increment_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "checkout_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_in_magento",
                        to="django_checkout.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order in Magento",
                "verbose_name_plural": "Orders in Magento",
            },
        ),
        migrations.CreateModel(
            name="ShipmentInMagento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("magento_url", models.CharField(max_length=255)),
                ("success", models.BooleanField(default=False)),
                ("request", models.JSONField()),
                ("response", models.JSONField(null=True)),
                ("shipment_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "checkout_shipping",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipping_in_magento",
                        to="django_checkout.shippingintent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping in Magento",
                "verbose_name_plural": "Shippings in Magento",
            },
        ),
    ]
